name: dbeaver_bookmarks
description: "Generate DBeaver Connections"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  file_picker: ^8.0.2
  fluent_ui: ^4.8.6
  flutter:
    sdk: flutter
  flutter_gen: ^5.9.0
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  freezed_annotation: ^2.4.4
  go_router: ^14.6.3
  hooks_riverpod: ^2.4.10
  intl: any
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.3.4
  uuid: ^4.5.1
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  go_router_builder: ^2.4.1
  json_serializable: ^6.9.3
  melos: ^6.0.0
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
  generate: true
